administration/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views
from . import gcal

app_name = 'administration'
urlpatterns = [
    path('', RedirectView.as_view(url='dashboard/')),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('customers/', views.CustomerPage.as_view(), name='customers'),
    path('customers/modify/option', views.CustomerOptions.as_view(), name='customers_nav_bar'),
    path('schedule/', views.Schedule.as_view(), name='schedule'),
    # Google Calendar integration
    path('schedule/google-events', gcal.google_events, name='google_events'),
    path('google/oauth/start', gcal.google_oauth_start, name='google_oauth_start'),
    path('google/oauth/callback', gcal.google_oauth_callback, name='google_oauth_callback'),
    path('google/oauth/disconnect', gcal.google_oauth_disconnect, name='google_oauth_disconnect'),
    path('staff/', views.StaffPage.as_view(), name='staff'),
    path('locations/', views.Locations.as_view(), name='locations'),
    path('permissions/', views.Admin.as_view(), name='admin'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('settings/contact/', views.settingsContact, name='settings-contact'),
    
    path('customers/search/', views.CustomersSearch.as_view(), name='customersearch'),
    path('profile/search/', views.ProfileSearch.as_view(), name='profilesearch'),
    path('staff/search/', views.StaffSearch.as_view(), name='staff_search'),
    path("ajax/room/select", views.ajax_for_selected_room_on_modal, name="ajax_for_selected_room_on_modal"),
    path("location/upload/waiver/", views.UploadWaiverView.as_view(), name="location_upload_waiver"),

    path('help/', views.Help.as_view(), name='help'),
    path('help/embed/', views.HelpEmbed.as_view(), name='helpEmbed'),
    path('help/email/', views.HelpEmail.as_view(), name='helpEmail'),
    
    path('staff/list/', views.StaffPage.as_view(), name='staff-list'),

    path('langselect/', (views.LanguageSelect.as_view()), name='language-select'),
    path('media/<str:path>', views.download_media, name='download_media'),
    path('export_profile', views.ExportProfile.as_view(), name='export_profile'),
    path('nolocation', views.no_location, name='no_location'),
]

customer/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'customer'
urlpatterns = [
    path('', (CustomerAccount.as_view()), name='customer-default'),
    path('account-settings/', CustomerAccountSettings.as_view(), name='customer-account-settings'),
    path('ajax/get_profile_results/', ajax_for_get_profile_results, name='get_profile_results'),
]

ruoom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from .views import PasswordResetViewRuoom
from . import views
from django.views.generic import RedirectView
from django.contrib import admin
from .forms import DomainPasswordResetForm
from .utils import load_plugin_urls

app_name = 'admin'

handler400 = 'ruoom.views.handler400'
handler403 = 'ruoom.views.handler403'
handler404 = 'ruoom.views.handler404'
handler500 = 'ruoom.views.handler500'

# Main router
urlpatterns = [
    path('registration/', include('registration.urls')),
    path('administration/', include('administration.urls')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('success/', views.success, name='success'),
    path('unsuccess/', views.unsuccess, name='unsuccess'),
    path('', RedirectView.as_view(url='administration/dashboard/')),
    path('save_studio_picture/', views.SaveStudioPictureView.as_view(), name='save_studio_picture'),
    path('save_profile_picture/', views.SaveProfilePictureView.as_view(), name='save_profile_picture'),
    path(
        'accounts/password_reset/', 
        PasswordResetViewRuoom.as_view(
            html_email_template_name='registration/password_reset_email.html',
            form_class = DomainPasswordResetForm
        ),
        name='password_reset'
    ),
    path('accounts/reset/done/', RedirectView.as_view(pattern_name='administration:dashboard')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

# Dynamically load plugin URLs
urlpatterns += load_plugin_urls()


# Add media url in development
if settings.DEFAULT_FILE_STORAGE == "django.core.files.storage.FileSystemStorage":
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
    )

# Add debug toolbar in development
if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

customer/models.py
from django.db import models

from administration.core.loading import get_model
from django.utils.translation import gettext_lazy as _

administration/views.py
from time import time as t_time
import json
from http import HTTPStatus
from datetime import datetime
import pytz
import csv
from django.conf import settings
from django.template.loader import render_to_string
from django.db.models import Q
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    Http404,
    StreamingHttpResponse,
    JsonResponse
)
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy

from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.utils.translation import pgettext, gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from security.key_lock import RuoomSecurity

from registration.forms import *
from registration.models import *

from .forms import *
from .helpers import is_ajax
from ruoom.automated_email_system import automated_email_send

# from weasyprint import HTML
from django.template.loader import render_to_string

from .models import Business, Location

from ruoom.settings import COUNTRY_LANGUAGES
import os

Profile = get_model("registration", "Profile")
Location = get_model("administration", "Location")
DaysOfOperation = get_model("administration", "DaysOfOperation")

# Create your views here.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEET_PER_METER = 3.28084

def read_file(filename):
    f = open(filename, 'r', encoding="utf-8")
    file_content = f.read()
    f.close()
    return file_content

def new_password_email_send(recipient_email,subject,customer_name,password_link,business_id=None):
    context = {
        'Customer_name': customer_name, 
        'password_link': password_link
    }

    html_content = render_to_string("../templates/emails/create-password.html", context)

    automated_email_send(recipient_email,subject,html_content,business_id)

    return JsonResponse({"message":"success"})

def reset_password_email_send(recipient_email,subject,customer,password_link,business_id=None):
    context = {
        'Customer': customer, 
        'password_link': password_link
    }
    html_content = render_to_string("../templates/emails/reset-password.html", context)

    automated_email_send(recipient_email,subject,html_content,business_id)

    return JsonResponse({"message":"success"})

def swap_request_email_send(recipient_email, subject, swap_request, shift_details, request, business_id=None):

    current_domain = 'http://{0}{1}'.format(request.get_host(),"/administration/download_swap_request_pdf")

    context = {
        'swap_request': swap_request, 
        'shift_details': shift_details, 
        'timestamp': datetime.now(), 
        "current_domain":current_domain,
        "message":subject
    }

    html_content = render_to_string("../templates/emails/staff-swap-request.html", context)

    automated_email_send([recipient_email],subject,html_content,business_id)

    return JsonResponse({"message":"success"})

def download_media(request, path):
    # Load file path
    file_path = os.path.join(
        settings.MEDIA_ROOT,
        path
    )

    # Check if file exist and return
    if os.path.exists(file_path):
        with open(file_path, "rb") as file:
            response = HttpResponse(
                file.read(),
                content_type="text/csv"
            )
            response["Content-Disposition"] = "inline; filename=%s" % (
                os.path.basename(file_path)
            )
            return response

    raise Http404

class Dashboard(TemplateView):
    template_name = 'administration/dashboard.html'

    def get(self, request):
        # Load params
        location_id = self.request.GET.get("location_id")

        # Prepare bar chart data for todays classes
        staff = request.user.profile

        # Load location filter
        location = None
        if staff.default_location and location_id is None:
            location = Location.objects.get(pk=int(staff.default_location.id))
        if location is None and location_id is None:
             # Prepare classes
            classes_queries = Q(
                business_id=request.user.profile.business_id
            )

        if location is None:
            # Load location filter
            location = Location.objects.filter(
                id=location_id,
                business_id=staff.business_id
            ).order_by('id').first()
            
        # Redirect if incorrect user type
        if not staff.user_type == Profile.USER_TYPE_STAFF:
            return redirect(settings.CUSTOMER_LOGIN_REDIRECT_URL)

        # Prepare list of locations
        location_list = Location.objects.filter(business_id=staff.business_id)

        # Prepare task
        if location:
            #task_queries = task_queries & Q(location=location)
            tz = pytz.timezone(Location.objects.get(id=location.id).time_zone_string)
        else:
            if Location.objects.filter(business_id=request.user.profile.business_id):
                tz = pytz.timezone(Location.objects.filter(business_id=request.user.profile.business_id).first().time_zone_string)
            else:
                tz = pytz.utc

        if location:
            classes_queries = classes_queries & Q(
                Q(room__location=location)
                | Q(layout__room__location=location)
                | Q(location_ref=location)
            )


        # Generate context
        context = {
            "dashboard": "active",
            "location_list": location_list,
            "location": location,
            'greeting_char': pgettext("Character after greeting person by name", " "),
            'date': datetime.now().astimezone(tz).date()
        }

        return render(request, self.template_name, context=context)

class CustomerOptions(TemplateView):
    template_name = "administration/customer_info_nav.html"
    context = {}

    def get(self, request):
        if request.GET.get("customer"):
            self.context["admin_customer_modify"] = "true"
            self.context["customer"] = request.GET.get("customer")
            self.context["customer_name"] = request.GET.get("customerName")
            self.context["customer_email"] = request.GET.get("customerEmail")
            self.context["customer_business_number"] =request.GET.get("customerBusinessNumber")
            self.context["customer_base_template"] = "administration/customers.html"
            return render(request, self.template_name, self.context)

class CustomerPage(FormView):
    template_name = "administration/customers.html"

    def get(self, request, customer_form=None):
        if not customer_form:
            customer_form = CreateCustomerForm()
        csv_form = ProfileCsvForm()
        business_id = request.user.profile.business_id
        studio_settings = Business.objects.filter(business_id=business_id).first()
        default_country_code = (
            studio_settings.default_country_code if studio_settings else "us"
        )
        customers = Profile.objects.filter(
            Q(user_type=Profile.USER_TYPE_CUSTOMER) | Q(user_type=Profile.USER_TYPE_STAFF),
            business_id=business_id
        ).order_by("first_name")
        args = {
            "customerspage": "active",
            "csv_form": csv_form,
            "customer_form": customer_form,
            "default_country_code": default_country_code,
            "customers": customers,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        if "new_customer" in request.POST:
            # Load form
            updated_request = request.POST.copy()
            updated_request["phone"] = updated_request["phone_with_code"]
            check_exist = Profile.objects.filter(
                Q(user_type=Profile.USER_TYPE_CUSTOMER) | Q(user_type=Profile.USER_TYPE_STAFF),
                email = updated_request["email"],
                business_id=request.user.profile.business_id)
            form = CreateCustomerForm(updated_request)
            if not check_exist:
                # Check valid form
                if form.is_valid():
                    form.save(request, request.user.profile.business_id)
                    return self.get(request)
            else:
                form.add_error('email', _("A user with this email already exists"))

            # Re render form if not valid
            args = {"customer_form": form, "open_customer_modal": "true"}
            return render(request, self.template_name, args)

        elif "new_csv" in request.POST:
            # Load form
            form = ProfileCsvForm(
                request.POST,
                request.FILES,
                request=request
            )

            # Check valid csv and message errors
            if not form.is_valid():
                for errors in form.errors.values():
                    for error_msg in errors:
                        messages.error(request, error_msg)
                return self.get(request)

            # Do import csv and report result
            form_result = form.save()
            imported = form_result.get("imported")
            fail_file = form_result.get("file")

            # Message import result
            messages.success(request, _(f"{imported} customer(s) imported succesfully."))
            if fail_file is not None:
                # Init link to file
                fail_url = reverse_lazy(
                    "administration:download_media",
                    args=[fail_file]
                )

                # Add message fail file
                messages.error(
                    request,
                    ''.join([f"<a href=\"{fail_url}\">",str(_("Please check this file for invalid data.")),"</a>"]),
                    extra_tags="safe"
                )

administration/templates/administration/customer_info_nav.html
{% load i18n %}
{% if admin_customer_modify == 'true' %}
    {% include "administration/customers.html" %}

{% endif %}

<div class="card customer-navigation">
    <div class="card-body position-relative">
        <ul class="nav nav-tabs nav-overflow header-tabs">
            <li class="{% if settings %}nav-item active {% else %} nav-item {% endif %}">
                <a class="nav-link "
                    href="{% url 'customer:customer-account-settings' %}?customer={{ customer }}&customerName={{ customer_name }}&customerBusinessNumber={{ customer_business_number }}">
                    {% trans "Account Settings" %} 
                </a>
            </li>
        </ul>

        <div class="position-absolute">
            <form class="mb-0" method="get" action="{% url 'administration:customers' %}">
                <button type="submit" class="btn btn-defalut my-2 my-sm-0">
                    <span class="fe fe-search"></span>
                    {% trans "Search Customer" %}
                </button>
            </form>
        </div>
    </div>
</div>

administration/templates/administration/help-center-emails.html
{% extends "navigation.html" %}
{% load static %}
{% load i18n %}

{% block subtitle %}Help Center{% endblock %}

{% block sub_head %}{% endblock %}

{% block content %}
  <div class="help-center pt-4">
      <div class="header">
        <div class="container-fluid">
          <h1 class="header-title mb-4">{% trans "Welcome to the Ruoom<sup>&reg;</sup> Help Center!" %}</h1>

          <div class="bg-white pr-4 pb-4 pl-4 rounded-lg tabs-header">

            <div class="row align-items-center">
              <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                  <li class="nav-item">
                    <a href="{% url 'administration:help'%}" class="nav-link">
                        <span class="fe fe-database mr-1"></span>
                        {% trans "Data" %}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'administration:helpEmail'%}" class="nav-link active">
                        <span class="fe fe-mail mr-1"></span>
                        {% trans "Emails" %}
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- end header -->

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Card -->
            <div class="card">
              <div class="card-body">
                  <div class="accordion" id="accordionHelp">

                        <div class="">
                            <div class="" id="headingOne">
                              <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left font-weight-bold text-16" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <i class="fa fa-lightbulb-o"></i>
                                    {% trans "How to set up email address for automated emails" %}
                                </button>
                              </h2>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionHelp">
                              <div class="pl-30 pr-30">
                                  <p class="mb-2">
                                  {% blocktrans %}To set up your email address as the address from which automated business emails are sent (think: registration confirmations, reminders, etc.), visit the "Platform Settings" page by clicking your user's name on the bottom-left corner. <u>NOTE</u>: Only certain users will have access to this page for security purposes.<br><br>

                                  Once on the "Platform Settings" page, you will see the section called, <i>Email information</i>. Fill in the email address information where you would like to send emails in the <i>Email information</i> section. Your email provider should inform you of these. Once you submit this information, your email setup is complete and ready to send automated emails!<br><br>

                                  If you happen to use Gmail or G-suite, the details should be as follows:<br><br>{% endblocktrans %}

                                  {% blocktrans %}<b>Details for Gmail or G-Suite:</b><br>
                                  Host Address: smtp.gmail.com<br>
                                  Host Port: 587<br>
                                  Host Using TLS: Yes<br><br>{% endblocktrans %}

                                  {% trans "<b>NOTE</b>: The Application Password field is not your regular log-in password for your email, but a password created explicitly for software integrations such as this. Here are the steps to generating an Application Password with a Gmail or G-suite based email address:" %}
                                  </p>
                                  <ol>
                                      {% blocktrans %}
                                      <li class="mb-2">On your Gmail page, click on your icon at the top right corner and select <i>Manage your Google Account</i>.</li>
                                      <li class="mb-2">On the left-hand bar, click <i>Security</i>.</li>
                                      <li class="mb-2">Under <i>Signing in to Google</i>, enable 2-factor authentication if it is not enabled yet.</li>
                                      <li class="mb-2">Again under <i>Signing in to Google</i>, select (or search for) <i>App Passwords</i>.</li>
                                      <li class="mb-2">Under <i>Type</i> select <i>Custom</i>, and type "Ruoom"</li>
                                      <li>Your new 16-digit application password will be displayed on the screen. If you lose this password, you'll need to generate a new one, so enter it ASAP.</li>
                                      {% endblocktrans %}
                                  </ol>
                              </div>
                            </div>
                        </div>
                    </div> <!-- end accordion -->
              </div>
            </div>
          </div>
        </div> <!-- / .row -->
      </div>
  </div>



{% endblock %}

administration/templates/administration/help-center.html
{% extends "navigation.html" %}
{% load static %}
{% load i18n %}

{% block subtitle %}Help Center{% endblock %}

{% block sub_head %}{% endblock %}

{% block content %}
  <div class="help-center pt-4">
      <div class="header">
        <div class="container-fluid">
          <h1 class="header-title mb-4">{% trans "Welcome to the Ruoom<sup>&reg;</sup> Help Center!" %}</h1>

          <div class="bg-white pr-4 pb-4 pl-4 rounded-lg tabs-header">

            <div class="row align-items-center">
              <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                  <li class="nav-item ">
                    <a href="{% url 'administration:help'%}" class="nav-link active">
                        <span class="fe fe-database mr-1"></span>
                        {% trans "Data" %}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'administration:helpEmail'%}" class="nav-link">
                        <span class="fe fe-mail mr-1"></span>
                        {% trans "Emails" %}
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- end header -->

      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Card -->
            <div class="card">
              <div class="card-body">
                  <div class="accordion" id="accordionHelp">
                        <div class="">
                            <div class="" id="headingOne">
                              <h2 class="mb-0">
                                <button class="btn btn-link btn-block text-left font-weight-bold text-16" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <i class="fa fa-lightbulb-o"></i>
                                    {% trans "How to set up business data" %}
                                </button>
                              </h2>
                            </div>

                            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionHelp">
                              <div class="pl-30 pr-30">
                                  <p>
                                  {% blocktrans %}Your business information, such as your business name, URL, and the name & email of your account, will be set up based on your form inputs from the beta site sign-up form.<br><br>

                                  To set up your first business location information, please follow these steps:<br><br>

                                  1) First, visit the "RoomO" page by clicking on the left side menu. When the page loads, select Add Location. Then, fill out the fields in the form.<br><br>

                                  2) If you have customer data you need to import, visit the "Customers" page on the left side menu. From there, click on the Import Customer Data feature button. For more guidance, see the <b>How to import customer data</b> guide below.<br><br>

                                  3) Visit "Platform Settings" to configure additional business information and third-party integrations (KakaoTalk, WhatsApp, email client, and payment processors). Those with administrator privileges can access Platform Settings by clicking their username in the bottom-left corner.<br><br>

                                  If you're having trouble setting up any of your data, do not hesitate to reach out to our support team at support@ruoomsoftware.com.<br><br>{% endblocktrans %}
                                  </p>
                              </div>
                            </div>
                        </div>


                        <div class="">
                          <div class="" id="headingTwo">
                            <h2 class="mb-0">
                              <button class="btn btn-link btn-block text-left collapsed font-weight-bold text-16" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                  <i class="fa fa-lightbulb-o"></i>
                                  {% trans "How to import customer data" %}
                              </button>
                            </h2>
                          </div>
                          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionHelp">
                            <div class="pl-30 pr-30">
                                <p>
                                {% blocktrans %}To import customer data from another program or database, you must first obtain a CSV copy of your customer data. To easily view CSV data, open the file with Microsoft Excel.<br><br>

                                Next, arrange the columns of the customer data in Microsoft Excel to match our input format. You can download an example of this format {% endblocktrans %}<a href="{% url 'administration:download_media' 'sample.csv' %}">{% trans "here" %}</a>.<br><br>

                                {% blocktrans %}Our data importer only looks at the header row at the top of each column. So as long as those column headers match the example format, your customer data will import without a problem!<br><br>

                                If there are any issues with the importing file, the platform will let you know. If you’re having trouble importing your customer data, don’t hesitate to reach out to our support team at support@ruoomsoftware.com.{% endblocktrans %}
                                </p>
                            </div>
                          </div>
                        </div>

                        <div class="">
                          <div class="" id="headingTwo">
                            <h2 class="mb-0">
                              <button class="btn btn-link btn-block text-left collapsed font-weight-bold text-16" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                  <i class="fa fa-lightbulb-o"></i>
                                  {% trans "Informing your customers about the Ruoom® platform migration" %}
                              </button>
                            </h2>
                          </div>
                          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionHelp">
                            <div class="pl-30 pr-30">
                                <p>
                                {% blocktrans %}Once you transfer your customer data to Ruoom®, you’ll need to request that your existing customers create a new password to access their accounts.

                                Using any email branding you’d like, add your unique reset password link below in the body of an email or a CTA button:<br><br>
                                
                                {{password_reset_link}}{% endblocktrans %}
                                </p>
                            </div>
                          </div>
                        </div>
                    </div> <!-- end accordion -->
              </div>
            </div>
          </div>
        </div> <!-- / .row -->
      </div>
  </div>



{% endblock %}

administration/templates/administration/settings.html
{% extends "navigation.html" %}
{% load static %}
{% load i18n %}

{% block subtitle %}{% trans "Platform Settings" %}{% endblock %}
{% block sub_head %}
{% endblock %}
{% block content %}

    <style>
        .text-color {
            color: {{ text_color }}
        }

        .text-color-bg {
            background-color: {{ text_color }}
        }
    </style>
    <div class="header">
        <div class="container-fluid">
          <h1 class="header-title my-4">{% trans "Platform Settings" %}</h1>
  
          <div class="bg-white pr-4 pb-4 pl-4 rounded-lg tabs-header">
  
            <div class="row align-items-center">
              <div class="col">
                <ul class="nav nav-tabs nav-overflow header-tabs">
                  <li class="nav-item">
                    <a href="{% url 'administration:settings-contact'%}" id="contact-tab" class="nav-link">
                        <span class="fe fe-mail mr-1"></span>
                        {% trans "Contact" %}
                    </a>
                  </li>
                  {% if 'payment' in plugins %}
                    {% include "payment/partials/settings_nav.html" %}
                  {% endif %}

                  {% if 'booking' in plugins %}
                    {% include "booking/partials/settings_nav.html" %}
                  {% endif %}

                  {% if 'messaging' in plugins %}
                    {% include "registration/partials/settings_nav.html" %}
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div> <!-- end header -->
  
      {% block settingscontent %}{% endblock %}

{% endblock %}