administration/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views
from . import gcal

app_name = 'administration'
urlpatterns = [
    path('', RedirectView.as_view(url='dashboard/')),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('customers/', views.CustomerPage.as_view(), name='customers'),
    path('customers/modify/option', views.CustomerOptions.as_view(), name='customers_nav_bar'),
    path('schedule/', views.Schedule.as_view(), name='schedule'),
    # Google Calendar integration
    path('schedule/google-events', gcal.google_events, name='google_events'),
    path('google/oauth/start', gcal.google_oauth_start, name='google_oauth_start'),
    path('google/oauth/callback', gcal.google_oauth_callback, name='google_oauth_callback'),
    path('google/oauth/disconnect', gcal.google_oauth_disconnect, name='google_oauth_disconnect'),
    path('staff/', views.StaffPage.as_view(), name='staff'),
    path('locations/', views.Locations.as_view(), name='locations'),
    path('permissions/', views.Admin.as_view(), name='admin'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('settings/contact/', views.settingsContact, name='settings-contact'),
    
    path('customers/search/', views.CustomersSearch.as_view(), name='customersearch'),
    path('profile/search/', views.ProfileSearch.as_view(), name='profilesearch'),
    path('staff/search/', views.StaffSearch.as_view(), name='staff_search'),
    path("ajax/room/select", views.ajax_for_selected_room_on_modal, name="ajax_for_selected_room_on_modal"),
    path("location/upload/waiver/", views.UploadWaiverView.as_view(), name="location_upload_waiver"),

    path('help/', views.Help.as_view(), name='help'),
    path('help/embed/', views.HelpEmbed.as_view(), name='helpEmbed'),
    path('help/email/', views.HelpEmail.as_view(), name='helpEmail'),
    
    path('staff/list/', views.StaffPage.as_view(), name='staff-list'),

    path('langselect/', (views.LanguageSelect.as_view()), name='language-select'),
    path('media/<str:path>', views.download_media, name='download_media'),
    path('export_profile', views.ExportProfile.as_view(), name='export_profile'),
    path('nolocation', views.no_location, name='no_location'),
]

customer/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'customer'
urlpatterns = [
    path('', (CustomerAccount.as_view()), name='customer-default'),
    path('account-settings/', CustomerAccountSettings.as_view(), name='customer-account-settings'),
    path('ajax/get_profile_results/', ajax_for_get_profile_results, name='get_profile_results'),
]

registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    path('signin/', views.UserSignin.as_view(), name='signin'),
    path('signup/', ((views.UserSignup.as_view())), name='signup'),
    path('signout/', (views.staff_signout), name='signout'),
    path('newpassword/', views.create_password, name='new-password'),
    
    path('customer/signin/', (views.CustomerSignIn.as_view()), name='customer_signin'),
]

ruoom/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.static import static
from .views import PasswordResetViewRuoom
from . import views
from django.views.generic import RedirectView
from django.contrib import admin
from .forms import DomainPasswordResetForm
from .utils import load_plugin_urls

app_name = 'admin'

handler400 = 'ruoom.views.handler400'
handler403 = 'ruoom.views.handler403'
handler404 = 'ruoom.views.handler404'
handler500 = 'ruoom.views.handler500'

# Main router
urlpatterns = [
    path('registration/', include('registration.urls')),
    path('administration/', include('administration.urls')),
    path('customer/', include('customer.urls')),
    path('admin/', admin.site.urls),
    path('success/', views.success, name='success'),
    path('unsuccess/', views.unsuccess, name='unsuccess'),
    path('', RedirectView.as_view(url='administration/dashboard/')),
    path('save_studio_picture/', views.SaveStudioPictureView.as_view(), name='save_studio_picture'),
    path('save_profile_picture/', views.SaveProfilePictureView.as_view(), name='save_profile_picture'),
    path(
        'accounts/password_reset/', 
        PasswordResetViewRuoom.as_view(
            html_email_template_name='registration/password_reset_email.html',
            form_class = DomainPasswordResetForm
        ),
        name='password_reset'
    ),
    path('accounts/reset/done/', RedirectView.as_view(pattern_name='administration:dashboard')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

# Dynamically load plugin URLs
urlpatterns += load_plugin_urls()


# Add media url in development
if settings.DEFAULT_FILE_STORAGE == "django.core.files.storage.FileSystemStorage":
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
    )

# Add debug toolbar in development
if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

templates/application.html
{% comment %}
{% load bootstrap4 %}
{% endcomment %}
{% load static %}
{% load i18n %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="Core code platform for Ruoom software">
  <meta name="author" content="Ruoom Inc.">

  <title>{% block title %}{% endblock %}</title>

  <!-- Libss CSS -->
  <link href="{% static 'fonts/feather/feather.min.css' %}" rel="stylesheet"/>
  <link href="{% static 'fonts/font-awesome/font-awesome.min.css' %}" rel='stylesheet' />

  <link href="{% static 'libs/flatpickr/dist/flatpickr.min.css' %}" rel="stylesheet"/>
  <link href="{% static 'libs/highlight.js/styles/vs2015.css' %}" rel="stylesheet"/>
  <link href="{% static 'libs/quill/dist/quill.core.css' %}" rel="stylesheet"/>
  <link href="{% static 'libs/select2/dist/css/select2.min.css' %}" rel="stylesheet"/>

  <!-- Theme CSS -->
  <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" id="stylesheetLight"/>
  <link rel="stylesheet" href="{% static 'css/custom-all.css' %}" id="stylesheetLight"/>
  <link rel="stylesheet" href="{% static 'css/bootstrap-tourist.css'%}"/>
  <link rel="stylesheet" href="{% static 'css/ruoom-tour.css'%}"/>

  <!-- custom css -->
  <link rel="stylesheet" href="{% static 'administration/css/croppie.css'%}" id="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/ruoom.css'%}" id="stylesheet" />
  <link  href="{% static 'css/dev-custom.css' %}" rel='stylesheet' />
  <link rel="stylesheet" href="{% static 'administration/css/admin-style.css'%}" id="stylesheet" />
  <link rel="stylesheet" href="{% static 'libs/mdb-color-picker/css/style.css' %}"></link>

  <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

  <!-- JS Libraries -->
  <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
  <script src="https://npmcdn.com/flatpickr/dist/l10n/ko.js"></script>

  <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'libs/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'libs/highlightjs/highlight.pack.min.js' %}"></script>
  <script src="{% static 'libs/flatpickr/dist/flatpickr.min.js' %}"></script>
  <script src="{% static 'libs/jquery-mask-plugin/dist/jquery.mask.min.js' %}"></script>
  <script src="{% static 'libs/list.js/dist/list.min.js' %}"></script>
  <script src="{% static 'libs/quill/dist/quill.min.js' %}"></script>
  <script src="{% static 'libs/dropzone/dist/min/dropzone.min.js' %}"></script>
  <script src="{% static 'libs/select2/dist/js/select2.min.js' %}"></script>
  <script src="{% static 'libs/chart.js/Chart.extension.min.js' %}"></script>
  <script src="{% static 'libs/tour-guide/bootstrap-tourist.js' %}"></script>
  <script src="{% static 'libs/tour-guide/tour-custom.js' %}"></script>

  <!-- JS Theme -->

  {% block sub_head %}{% endblock %}

  <script type="text/javascript">
    
    $(function () {
      $('[data-toggle="tooltip"]').popover({
        trigger:"hover",
        title: function(){
          return "";
        },
        content: function() {
          var content = "";
          if($(this).attr("data-original-title") != undefined && $(this).attr("data-original-title") != ""){
            content = $(this).attr("data-original-title");
          }else if($(this).attr("data-content") != undefined && $(this).attr("data-content") != ""){
            content = $(this).attr("data-content");
          }else if($(this).attr("title") != undefined && $(this).attr("title") != ""){
            content = $(this).attr("title");
          }
          return content;
        }
      });
    });
  </script>
</head>

<body>

  {% block body %}{% endblock %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>

  <script src="{% static 'libs/croppie/croppie.js' %}"></script>
  <script src="{% static 'js/dev-custom.js' %}"></script>
  
  <div id="formSuccessModel" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="modelTitle">{% trans "Saved" %}</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <h4 class="text-success text-center mt-2" id="modelBodyText">{% trans "Updated Successfully!" %}</h4>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

templates/customer-navigation.html
{% extends "application.html" %}
{% load static %}
{% load language_verbose %}
{% load i18n %}

{% load custom_tags %}

{% block title %}
  {{business_name}} |
  {% block subtitle %}{% endblock %}
{% endblock %}

{% block body %}

{% get_current_language as LANGUAGE_CODE %}

  <nav class="navbar navbar-expand navbar-light navbar-top">
    <div class="container-fluid">

      <!-- Brand -->
      <a class="navbar-brand">
        <h1 class="header-title" id="already_registred_message">{% trans "Account" %}</h1>
      </a>

      <!-- Collapse -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown mr-3">
              <a href="#" id="language" class="dropdown-toggle nav-link pt-2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="fe fe-globe"></span>
                  {{request.LANGUAGE_CODE|language_verbose}}
              </a>

              <div class="dropdown-menu border" aria-labelledby="language">
                {% for language_code, language_name in languages.items %}
                  {% if language_code != request.user.profile.language %}
                    <form method="post" id="language_select_form" class="mb-0" enctype="multipart/form-data" action="{% url 'administration:language-select' %}" >
                      {% csrf_token %}
                      <input name="language" value="{{language_code}}" hidden="true">
                      <button class="dropdown-item d-md-block" name="language_select_form" type="submit">{{language_name}}</button>
                    </form>
                  {% endif %}
                {% endfor %}
              </div>

            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <div class="avatar-name d-inline-block text-center {% if LANGUAGE_CODE != "ko" %} inside-circle{% endif %}">{{request.user.profile.localized_initials}}</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right border" aria-labelledby="navbarDropdown">

                  <a href="{% url 'customer:customer-account-settings'%}" class="dropdown-item">
                      <span class="fe fe-user mr-2"></span>{% trans "My Account" %}
                  </a>

                  {% if request.user.is_authenticated %}
                    <a href="/registration/signout/" class="dropdown-item">
                      <span class="fe fe-log-out mr-2"></span> {% trans "Sign Out" %}
                    </a>
                  {% endif %}
                </div>
            </li>
        </ul>

        <!-- Divider -->
        <div class="mt-auto"></div>
  </nav>


  <div class="main-content">
    {% block content %}{% endblock %}
  </div>
{% endblock %}

templates/error.html
{% extends "application.html" %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "404" %}{% endblock %}

{% block body %}

<div class="container">
    <div class="row align-items-center">
        <div class="col-12 col-md-6 offset-xl-2 offset-md-1 order-md-2 mb-5 mb-md-0">

          <div class="text-center">
            <img src="{% static 'img/lost.svg' %}" alt="icon" class="img-fluid" />
          </div>

        </div>
        <div class="col-12 col-md-5 col-xl-4 order-md-1 my-5">
          
          <div class="text-center">

            <h1 class="display-4 mb-3">{% trans "Oops! There’s no page here 😟" %}</h1>
            <p>{% trans "We've hit a small snag! Back up and try again" %}</a></p>
          
          </div>

        </div>
    </div>
</div>

{% endblock %}

templates/navigation.html
{% extends "application.html" %}
{% load static %}
{% load language_verbose %}
{% load i18n %}
{% load custom_tags %}
{% block title %}
{% trans "Administration" %} |
{% block subtitle %}{% endblock %}
{% endblock %}
{% block body %}
<style>
   .select2-results__option:empty  {
   display: none !important;
   }
   .dynamic-field {
   border-bottom: 1px dashed black;
   outline: none;
   font-weight: bold;
   }
   .template_text {
   white-space: pre-line;
   border: 1px solid #d2ddec;
   padding: 10px;
   border-radius: 5px;
   min-height: 150px;
   max-height: 300px;
   overflow: auto;
   }
   .bold {
   font-weight: bold;  
   }
   div.editable {
   width: 300px;
   height: 200px;
   border: 1px solid #ccc;
   padding: 5px;
   }
   .popover{
      max-width: 300px;
   }
   .nav-link{
      color: #FFFFFF;
   }
</style>
<style type="text/css">
   input {font-weight:bold;}
</style>
<nav class="navbar navbar-vertical fixed-left navbar-expand-lg" id="sidebar">
   <div class="container-fluid">
   <!-- Toggler -->
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
   <span></span>
   <span></span>
   <span></span>
   </button>
   <!-- Brand -->
   <label class="cabinet center-block text-center">
      <figure>
         {% if 'ruoom_logo' in studio_setting_image %}
         <img src="{% static studio_setting_image %}" class="navbar-brand-img mx-auto rounded-circle" id="item-img-output" alt="logo" />
         <figcaption><i class="fa fa-camera"></i></figcaption>
         {% else %}
         <img src="{% get_media_prefix %}{{studio_setting_image}}" class="navbar-brand-img mx-auto rounded-circle" id="item-img-output" alt="logo" />
         <figcaption><i class="fa fa-camera"></i></figcaption>
         {% endif %}
      </figure>
      <form id="ajax_upload_studio_form" method="POST" action="{% url 'save_studio_picture'%}" style="display: none">
         <input type="file" class="item-img file center-block" name="studio_image" {% disable_if_not_admin user=request.user %}/>
         <input type="submit" />
      </form>
   </label>
   <!-- Collapse -->
   <div class="collapse navbar-collapse" id="sidebarCollapse">
      <!-- Navigation mb-md-4"-->
      <ul class="navbar-nav" >
         <li class="nav-item" id="dashboard-content">
            <a class="nav-link {{dashboard}}" href="{% url 'administration:dashboard'%}">
            <i class="fe fe-home"></i> {% trans "Home" %}
            </a>
         </li>
         <li class="nav-item" id="customers-page">
            <a style="display:{% display_if_has_access user=request.user permission_group='customers' %}"  class="nav-link {{customerspage}}" href="{% url 'administration:customers'%}">
            <i class="fe fe-users"></i>{% trans "Customers" %}
            </a>
         </li>
         <li class="nav-item" id="schedule-page">
            <a style="display:{% display_if_has_access user=request.user permission_group='schedule' %}"  class="nav-link {{schedule}}" href="{% url 'administration:schedule'%}">
            <i class="fe fe-calendar"></i>{% trans "Schedule" %}
            </a>
         </li>
         {% if store_plugins %}
            {% include 'partials/store_top_nav.html' %}
         {% endif %}
      </ul>
      <!-- Divider -->
      <hr class="navbar-divider my-2">
      <!-- Heading -->
      <h4 class="mt-3 text-white">{% trans "Admin Pages" %}</h4>
      <!-- <- Navigation -->
      <ul class="navbar-nav mb-md-4">
         <li class="nav-item" id="staff-page">
            <a style="display:{% display_if_has_access user=request.user permission_group='staff' %}"  class="nav-link {{staffpage}}" href="{% url 'administration:staff'%}">
            <i class="fe fe-user"></i>{% trans "Staff" %}
            </a>
         </li>
         {% if 'payment' in plugins %}
            {% include 'payment/partials/purchases_nav.html' %}
         {% endif %}
         <li class="nav-item" id="ruoom-planner-page">
            <a style="display: {% display_if_has_access user=request.user permission_group='locations' %}"  class="nav-link {{locations}}" href="{% url 'administration:locations'%}">
               <i class="fe fe-map-pin"></i>{% trans "Locations" %}
            </a>
         </li>
         <li class="nav-item" id="permissions-page">
            <a style="display: {% display_if_has_access user=request.user permission_group='admin' %}"  class="nav-link {{permissions}}" href="{% url 'administration:admin'%}">
            <i class="fe fe-lock"></i>{% trans "Permissions" %}
            </a>
         </li>
      </ul>
      <hr class="navbar-divider my-2">
      <div class="mt-auto"></div>

      <div class="dropup mt-2">
         <a href="#" id="language" class="dropdown-toggle text-white" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <span class="fe fe-globe"></span>
         {{request.user.profile.language|language_verbose}}
         </a>
         <div class="dropdown-menu" aria-labelledby="language">
            {% for language_code, language_name in languages.items %}
            {% if language_code != request.user.profile.language %}
            <form method="post" id="language_select_form" class="mb-0" enctype="multipart/form-data" action="{% url 'administration:language-select' %}" >
               {% csrf_token %}
               <input name="language" value="{{language_code}}" hidden="true">
               <button class="dropdown-item d-md-block" name="language_select_form" type="submit">{{language_name}}</button>
            </form>
            {% endif %}
            {% endfor %}
         </div>
      </div>
      <hr class="navbar-divider my-3">
      <div class="dropup mb-3">
         <!-- Toggle -->
         <a href="#" id="sidebarIconCopy" class="dropdown-toggle text-white" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         {{ request.user.profile.localized_name }}
         </a>
         <!-- Menu -->
         <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
            <div>
               <a href="/administration/help" class="dropdown-item">{% trans "Help Center" %}</a>
               <hr class="dropdown-divider">
            </div>
            <div style="display: {% display_if_has_access user=request.user permission_group='admin' %}">
               <a href="/administration/settings" class="dropdown-item">{% trans "Platform Settings" %}</a>
               <hr class="dropdown-divider">
            <div>
            {% if request.user.is_authenticated %}
            <a href="/registration/signout/" class="dropdown-item">{% trans "Sign Out" %}</a>
            {% endif %}
         </div>
      </div>
   </div>
</nav>
<div class="main-content">
   {% block content %}{% endblock %}
</div>

<div class="modal fade" id="first-time-modal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered modal" role="document">
      <div class="modal-content">
         <div class="modal-header d-block">
            <h3 class="modal-title mb-2 fw-bold d-inline-block">{% trans "Please Create a Password For Your New Ruoom® Platform" %}</h3>
         </div>
         <form method="post" id="new_password_form" class="mb-0" enctype="multipart/form-data" action="{% url 'registration:new-password' %}" >
            {% csrf_token %}
            <div class="modal-body pb-0">

               <!-- Input -->
               <div class="form-group">
                  <input type="password" name="password" class="form-control form-control-appended" placeholder='{% trans "Password" %}' required="" id="id_password" autocomplete="off" style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: pointer;">
               </div> 
               <div class="form-group">
                  <input type="password" name="password_again" class="form-control form-control-appended" placeholder='{% trans "Repeat Password" %}' required="" id="id_password_again" autocomplete="off" style="background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: pointer;">
               </div>
               <div class="form-group mb-5" id="new_pass_error" style="display: none;">
                  <p style="color: red">{% trans "Passwords must match" %}</p>
               </div>
            </div>
            <input type="hidden" value="True" name="new_password_form">

         </form>
         <div class="modal-footer justify-content-start">
            <button class="btn btn-primary" id="new_password_submit" onclick="newPassValidate()">{% trans "Submit" %}</button>
         </div>
      </div>
   </div>
</div>
<div class="modal fade" id="deactivated-modal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered modal" role="document">
      <div class="modal-content">
         <div class="modal-header d-block">
            <h3 class="modal-title mb-2 fw-bold d-inline-block">{% trans "Your Staff Account Has Been Deactivated" %}</h3>
         </div>
         <div class="modal-body p-4">
            <p class="mb-0 font-italic">{% trans "Please contact your business administrator" %}</p>
         </div>
      </div>
   </div>
</div>
<div class="modal fade" id="cropImagePop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">
               <?=multiLanguage( "Edit Foto" , "Edit Photo" )?>
            </h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         </div>
         <div class="modal-body">
            <div id="upload-demo" class="center-block"></div>
         </div>
         <div class="modal-footer justify-content-center">
            <button type="button" class="btn btn-default mr-3" data-dismiss="modal">{% trans "Cancel" %}</button>
            <button type="button" id="cropImageBtn" class="btn btn-primary">{% trans "Crop" %}</button>
         </div>
      </div>
   </div>
</div>

{{ templates|json_script:"templates" }}
{{ templates_error|json_script:"templates_error" }}
<script type="text/javascript">
   let dynamicVariables = [];
   var userLanguage = "{{request.user.profile.language}}";
   if (userLanguage == "ko"){
     flatpickr.localize(flatpickr.l10ns.ko); 
   }
   
   function onChangeDynamicField(element, defaultValue) {
     if (!element.innerText.length) {
       element.innerText = element.id;
     }
   }
   
   //Handle Popups   
   //First time sign-on password logic & more
   if ("{{request.user.profile.staff_is_active}}" == "False") {
      $('#deactivated-modal').modal({
           backdrop: 'static',
           keyboard: false
       });
      $('#deactivated-modal').modal('show');
   }
   else if("{{first_time}}" == "True") {
      $('#first-time-modal').modal({
           backdrop: 'static',
           keyboard: false
       });
      $('#msa-sign-modal').modal('hide');
      $('#first-time-modal').modal('show');
   }

   var newpassform = document.getElementById("new_password_form");
   //document.getElementById("new_password_submit").addEventListener("click", function () {
   function newPassValidate() {
      pass1 = $("#id_password").val()
      pass2 = $("#id_password_again").val()
      if (pass1 != pass2) {
         $("#new_pass_error").show()
      } else {
         $("#new_pass_error").hide()
         newpassform.submit();
      }
   };
   </script>
{% endblock %}